In this project, I achieved the following;
Tumworobere/Budget-Tracker pull request #4
Opened 2022-04-23 18:06 UTC by Tumworobere

- Created models according to the given ERD diagram.
   - Implemented the authentication and authorization with devise.
   - Created the page to add a category.
   - Created the home page.
   - Created the page to add a transaction.
   - Created the transactions page.
   - Tested the app using RSpec.

2022-04-23 19:34 UTC, rukundoeric requested changes
Hi @Tumworobere, 

_Great job so far 👏 💯 👍. However, there are few issues we need to address before we move on. Please, check the comments below._
## Highlights
  - Follows git workflow.  💯
  - Codebase looks clean and professional. 💯 


## Required Changes ♻️
  - [ ] Some of your tests are still failing. Kindly address the issue and fix it.
  ![Screen Shot 2022-04-23 at 21 27 27](https://user-images.githubusercontent.com/45217364/164943535-78209114-241b-4531-9ef2-0c82e1f6af4b.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
  - [ ] It is not in the project requirements, but It would be nice to fix the[ N+1 problem](https://medium.com/doctolib/understanding-and-fixing-n-1-query-30623109fe89)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-23 21:55 UTC, mmsesay requested changes
Hi @Tumworobere, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-04-23 21:55 UTC, mmsesay commented on spec/integration/group_index_spec.rb
>      end
- [ ] I will suggest you fix your tests. You still have some that are failing. The `group_index_spec.rb` is just one of them.
Please see the screenshot to see that you still have 6 failing tests that need retouching.

Test Screenshot |
:---------------------:|
![a1](https://user-images.githubusercontent.com/39523312/164947068-390d9898-88b3-4941-b8e5-1cd73e710842.png)

2022-04-23 23:18 UTC, Gambit142 requested changes
Hi @Tumworobere 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-23 23:18 UTC, Gambit142 commented on spec/integration/group_show_spec.rb
> +      fill_in('Password', with: 'samu@2022')
- [ ] I know you have tried working on the tests but currently six of them do not pass. This is the error I get when I run the command for the test

![image](https://user-images.githubusercontent.com/77106962/164949112-b2fcfab4-b6f1-43ff-8a72-20fc7d88f5c1.png)

This is most likely from the way you are linking the buttons. Kindly fix this. 👍

2022-04-26 09:21 UTC, sinansevgi approved these changes
Hi @Tumworobere, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

[Optional]

- [ ] The Rails asset pipeline automatically loads both the CSS and SCSS files and cannot compile the view because you have two stylesheets with the same name (application.scss and application.css). This is why tests seem to fail. When I remove the `application.scss` file and try to run the tests, I can see that all tests are passing successfully. In order to prevent this from happening, you can remove one of the files.

Happy Hacking! :computer: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Sinan Sevgi

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-26 09:49 UTC, Tumworobere commented
> Hi @Tumworobere,
> 
> Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉
> 
> [Optional]
> 
>     * [ ]  The Rails asset pipeline automatically loads both the CSS and SCSS files and cannot compile the view because you have two stylesheets with the same name (application.scss and application.css). This is why tests seem to fail. When I remove the `application.scss` file and try to run the tests, I can see that all tests are passing successfully. In order to prevent this from happening, you can remove one of the files.
> 
> 
> Happy Hacking! 💻
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Sinan Sevgi
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thank you very much @sinansevgi  for this approval

2022-04-26 16:04 UTC, merged